# Generated by Django 4.0.4 on 2022-07-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_statistics', 'Can view statistics')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
